# Generated by Django 3.1 on 2020-08-26 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_auto_20200825_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_track',
            old_name='author',
            new_name='user_name',
        ),
    ]
