# Generated by Django 3.1 on 2020-08-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_auto_20200826_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_track',
            name='body',
        ),
        migrations.AddField(
            model_name='user_track',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
